version: '3.7'
services:
  db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: bookings_redis


  booking:
    image: booking_image
    build:
      context: .
    env_file:
      - .env-non-dev

    container_name: booking_app
    depends_on:
      - db
      - redis


